nginx renewal fixes, oauth mastodon setup, secret restructure, etc

diff --git a/mastodon/setup b/mastodon/setup
--- a/mastodon/setup
+++ b/mastodon/setup
@@ -18,40 +18,39 @@ OTP_SECRET=000000
 OIDC_CLIENT_SECRET=000000
 EOF
 
+# have to bring it all down before we touch the files
+docker-compose down
+
 if [ -z "$MASTODON_SKIP_DB_INIT" ]; then
 	info "configuring mastodon"
-	sudo docker-compose run web \
+	sudo docker-compose run --rm mastodon \
 	  rails db:setup \
 	|| die "unable to login"
 fi
 
-# now create the real secrets file
-echo > env.secrets "# DO NOT CHECK IN"
+OIDC_CLIENT_SECRET="$(openssl rand -hex 32)"
 
-sudo docker-compose run web \
+# now create the real secrets file,
+# along with some parameters that should be in the environment
+cat <<EOF > env.secrets
+# DO NOT CHECK IN
+LOCAL_DOMAIN=$MASTODON_HOSTNAME
+OIDC_DISPLAY_NAME=$REALM
+OIDC_ISSUER=https://$KEYCLOAK_HOSTNAME/realms/$REALM
+OIDC_REDIRECT_URI=https://$MASTODON_HOSTNAME/auth/auth/openid_connect/callback
+OIDC_CLIENT_SECRET=$OIDC_CLIENT_SECRET
+SECRET_KEY_BASE=$(openssl rand -hex 32)
+OTP_SECRET=$(openssl rand -hex 32)
+EOF
+
+docker-compose run --rm mastodon \
   rails mastodon:webpush:generate_vapid_key \
   >> env.secrets \
 || die "unable to generate vapid key"
 
-echo "SECRET_KEY_BASE=$(openssl rand -hex 32)" >> env.secrets
-echo "OTP_SECRET=$(openssl rand -hex 32)" >> env.secrets
 
-CLIENT_SECRET="$(openssl rand -hex 32)"
-echo "OIDC_CLIENT_SECRET=$CLIENT_SECRET" >> env.secrets
-
-# create the keycloak side of the secret
-cd ../keycloak
-source env.production
-
-sudo docker-compose exec -T keycloak \
-  /opt/keycloak/bin/kcadm.sh \
-  create clients \
-  --server http://localhost:8080/ \
-  --user admin \
-  --password "$KEYCLOAK_ADMIN_PASSWORD" \
-  --realm master \
-  -r "$REALM" \
-  -f - <<EOF || die "unable to create client id"
+../keycloak/client-delete mastodon
+../keycloak/client-create <<EOF || die "Unable to create keycloak client"
 {
 	"clientId": "mastodon",
 	"rootUrl": "https://$MASTODON_HOSTNAME/",
@@ -59,6 +58,8 @@ sudo docker-compose exec -T keycloak \
 	"redirectUris": [ "https://$MASTODON_HOSTNAME/*" ],
 	"webOrigins": [ "https://$MASTODON_HOSTNAME" ],
 	"clientAuthenticatorType": "client-secret",
-	"secret": "$CLIENT_SECRET"
+	"secret": "$OIDC_CLIENT_SECRET"
 }
 EOF
+
+docker-compose up -d
diff --git a/nextcloud/setup b/nextcloud/setup
--- a/nextcloud/setup
+++ b/nextcloud/setup
@@ -3,23 +3,25 @@ die() { echo >&2 "$@" ; exit 1 ; }
 
 DIRNAME="$(dirname $0)"
 cd "$DIRNAME"
-[ -r env.production ] && source env.production
-[ -r ../env.production ] && source ../env.production
+source ../env.production || die "no top level env?"
+source env.production || die "no local env?"
 
-sudo docker-compose exec -u www-data -T nextcloud \
-  ./occ app:install sociallogin \
-|| die "unable to install sociallogin app"
+if [ ! -r "env.secrets" ]; then
+	NEXTCLOUD_CLIENT_SECRET="$(openssl rand -hex 32)"
+	NEXTCLOUD_ADMIN_PASSWORD="$(openssl rand -hex 4)"
 
-sudo docker-compose exec -u www-data -T nextcloud \
-  ./occ config:app:set sociallogin prevent_create_email_exists --value=1 \
-|| die "unable to config sociallogin"
-
-sudo docker-compose exec -u www-data -T nextcloud \
-  ./occ config:app:set sociallogin update_profile_on_login --value=1 \
-|| die "unable to config sociallogin"
+	echo "Generating secrets: admin password $NEXTCLOUD_ADMIN_PASSWORD"
+	cat <<EOF > env.secrets
+# Do not check in!
+NEXTCLOUD_ADMIN_PASSWORD=$NEXTCLOUD_ADMIN_PASSWORD
+NEXTCLOUD_TRUSTED_DOMAINS=$NEXTCLOUD_HOSTNAME
+NEXTCLOUD_CLIENT_SECRET=$NEXTCLOUD_CLIENT_SECRET
+EOF
+else
+	source env.secrets || die "no secret env?"
+fi
 
 BASE="https://$KEYCLOAK_HOSTNAME/realms/$REALM/protocol/openid-connect"
-SECRET="$(openssl rand -hex 20)"
 PROVIDER="$(jq -c . <<EOF
 {
 	"custom_oidc": [
@@ -27,15 +29,15 @@ PROVIDER="$(jq -c . <<EOF
 			"name":		"keycloak",
 			"title":	"Keycloak",
 			"clientId":	"nextcloud",
-			"clientSecret":	"$SECRET",
+			"clientSecret":	"$NEXTCLOUD_CLIENT_SECRET",
 			"authorizeUrl":	"$BASE/auth",
 			"tokenUrl":	"$BASE/token",
 			"userInfoUrl":	"$BASE/userinfo",
-			"logoutUrl":	"",	
-			"displayNameClaim": "",
+			"logoutUrl":	"$BASE/logout",
 			"scope":	"openid",
 			"groupsClaim":	"roles",
 			"style":	"keycloak",
+			"displayNameClaim": "",
 			"defaultGroup":	""
 		}
 	]
@@ -43,26 +45,27 @@ PROVIDER="$(jq -c . <<EOF
 EOF
 )"
 
-sudo docker-compose exec -u www-data -T nextcloud \
-  ./occ config:app:set \
-  sociallogin custom_providers \
-  --value="$PROVIDER" \
-|| die "unable to set keycloak parameters"
+
+docker-compose up -d || die "unable to bring up docker"
+
+# wait for the nextcloud instance to be responsive
+# TODO: how to find out if it is ready?
+echo "SLEEPING..."
+sleep 30
 
 
-# create the keycloak side of the secret
-cd ../keycloak
-source env.production
 
-sudo docker-compose exec -T keycloak \
-  /opt/keycloak/bin/kcadm.sh \
-  create clients \
-  --server http://localhost:8080/ \
-  --user admin \
-  --password "$KEYCLOAK_ADMIN_PASSWORD" \
-  --realm master \
-  -r "$REALM" \
-  -f - <<EOF || die "unable to create client id"
+docker-compose exec -u www-data -T nextcloud bash -x <<EOF || die "unable to configure sociallogin"
+./occ app:remove sociallogin || echo "not yet installed"
+./occ app:install sociallogin || exit 1
+./occ config:app:set sociallogin prevent_create_email_exists --value=1 || exit 1
+./occ config:app:set sociallogin update_profile_on_login --value=1 || exit 1
+./occ config:app:set sociallogin custom_providers --value='$PROVIDER' || exit 1
+EOF
+
+../keycloak/client-delete 'nextcloud' || echo "client did not exist?"
+
+../keycloak/client-create << EOF || die "unable to create client id"
 {
 	"clientId": "nextcloud",
 	"rootUrl": "https://$NEXTCLOUD_HOSTNAME/",
@@ -70,6 +73,6 @@ sudo docker-compose exec -T keycloak \
 	"redirectUris": [ "https://$NEXTCLOUD_HOSTNAME/*" ],
 	"webOrigins": [ "https://$NEXTCLOUD_HOSTNAME" ],
 	"clientAuthenticatorType": "client-secret",
-	"secret": "$SECRET"
+	"secret": "$NEXTCLOUD_CLIENT_SECRET"
 }
 EOF
diff --git a/nginx/setup b/nginx/setup
--- a/nginx/setup
+++ b/nginx/setup
@@ -1,28 +1,39 @@
 #!/bin/bash
 die() { echo >&2 "$@" ; exit 1 ; }
 
-ENV=env.production
-if [ ! -r "$ENV" ]; then
-	die "$ENV: not found?"
-fi
+DIRNAME="$(dirname $0)"
+cd "$DIRNAME"
 
-source ../env.production
-source env.production
+source ../env.production || die "no top level env"
+source env.production || die "no local env"
 
 if [ -z "${DOMAIN_NAME}" ]; then
 	die "DOMAIN_NAME not set"
 fi
 
+docker-compose down
+
 certdir="data/certbot/conf/live/${DOMAIN_NAME}"
 mkdir -p "$certdir" || die "$certdir: unable to make"
 
-openssl req \
-	-x509 \
-	-newkey rsa:2048 \
-	-keyout "$certdir/privkey.pem" \
-	-out "$certdir/fullchain.pem" \
-	-sha256 \
-	-nodes \
-	-days 365 \
-	-subj "/CN=${DOMAIN_NAME}'" \
-|| die "$certdir/privkey.pem: unable to create temp key"
+if [ ! -r "$certdir/privkey.pem" ]; then
+	openssl req \
+		-x509 \
+		-newkey rsa:2048 \
+		-keyout "$certdir/privkey.pem" \
+		-out "$certdir/fullchain.pem" \
+		-sha256 \
+		-nodes \
+		-days 365 \
+		-subj "/CN=${DOMAIN_NAME}'" \
+	|| die "$certdir/privkey.pem: unable to create temp key"
+fi
+
+docker-compose up -d || die "unable to bring up nginx"
+
+echo "SLEEPING..."
+sleep 10
+
+./certbot-renew || die "unable to create certs"
+
+
