setup: make all the scripts do the right thing and run through a full rebuild

diff --git a/grafana/setup b/grafana/setup
--- a/grafana/setup
+++ b/grafana/setup
@@ -8,12 +8,18 @@ source env.production || die "no local env?"
 
 BASE="https://$KEYCLOAK_HOSTNAME/realms/$REALM/protocol/openid-connect"
 
-if [ ! -r "env.secrets" ]; then
-	GRAFANA_CLIENT_SECRET="$(openssl rand -hex 32)"
-	GRAFANA_ADMIN_PASSWORD="$(openssl rand -hex 4)"
+if [ -r "env.secrets" ]; then
+	docker-compose up -d || die "grafana: unable to start container"
+	exit 0
+fi
 
-	echo "Generating secrets: admin password $GRAFANA_ADMIN_PASSWORD"
-	cat <<EOF > env.secrets
+docker-compose down 2>/dev/null
+
+GRAFANA_CLIENT_SECRET="$(openssl rand -hex 32)"
+GRAFANA_ADMIN_PASSWORD="$(openssl rand -hex 4)"
+
+echo "Generating secrets: admin password $GRAFANA_ADMIN_PASSWORD"
+cat <<EOF > env.secrets
 # Do not check in!
 GF_SECURITY_ADMIN_PASSWORD=$GRAFANA_ADMIN_PASSWORD
 GF_SERVER_ROOT_URL=https://$GRAFANA_HOSTNAME/
@@ -23,13 +29,9 @@ GF_AUTH_GENERIC_OAUTH_TOKEN_URL=$BASE/token
 GF_AUTH_GENERIC_OAUTH_API_URL=$BASE/userinfo
 GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=$GRAFANA_CLIENT_SECRET
 EOF
-else
-	source env.secrets || die "no secret env?"
-fi
 
-docker-compose down
 
-../keycloak/client-delete 'grafana' || echo "client did not exist?"
+../keycloak/client-delete 'grafana' 2>/dev/null
 
 ../keycloak/client-create << EOF || die "unable to create client id"
 {
@@ -43,4 +45,4 @@ docker-compose down
 }
 EOF
 
-docker-compose up -d || die "unable to bring up grafana"
+docker-compose up -d || die "grafana: unable to bring up container"
diff --git a/hedgedoc/setup b/hedgedoc/setup
--- a/hedgedoc/setup
+++ b/hedgedoc/setup
@@ -6,14 +6,19 @@ cd "$DIRNAME"
 source ../env.production || die "no top levle env?"
 source env.production || die "no local env?"
 
-docker-compose down
+if [ -r "./env.secrets" ]; then
+	docker-compose up -d || die "hedgedoc: unable to start"
+	exit 0
+fi
+
+docker-compose down 2>/dev/null
 
 # regenerate the client secrets
 CLIENT_SECRET="$(openssl rand -hex 20)"
 SESSION_SECRET="$(openssl rand -hex 20)"
 
-rm -f env.secrets
 cat <<EOF > env.secrets
+# DO NOT CHECK IN
 CMD_OAUTH2_CLIENT_SECRET=$CLIENT_SECRET
 CMD_SESSION_SECRET=$SESSION_SECRET
 EOF
@@ -46,5 +51,4 @@ EOF
 }
 EOF
 
-
-docker-compose up -d || die "unable to start container"
+docker-compose up -d || die "hedgedoc: unable to start container"
diff --git a/keycloak/setup b/keycloak/setup
--- a/keycloak/setup
+++ b/keycloak/setup
@@ -6,10 +6,29 @@ DIRNAME="$(dirname $0)"
 cd "$DIRNAME"
 source ../env.production
 source ./env.production
-source ./env.secrets
+
+if [ -r "./env.secrets" ]; then
+	docker-compose up -d || die "keycloak: unable to start container"
+	exit 0
+fi
+
+docker-compose down 2>/dev/null
+
+KEYCLOAK_ADMIN_PASSWORD="$(openssl rand -hex 8)"
+echo "Keycloak admin password $KEYCLOAK_ADMIN_PASSWORD"
+
+cat <<EOF > env.secrets
+# DO NOT CHECK IN
+KEYCLOAK_ADMIN_PASSWORD=$KEYCLOAK_ADMIN_PASSWORD
+EOF
+
+docker-compose up -d || die "unable to start keycloak"
+echo "sleeping a minute while keycloak initializes..." 
+sleep 30
+
 
 info "logging into server"
-sudo docker-compose exec keycloak \
+docker-compose exec keycloak \
   /opt/keycloak/bin/kcadm.sh \
   config credentials \
   --server http://localhost:8080/ \
@@ -20,7 +39,7 @@ sudo docker-compose exec keycloak \
 
 
 info "Create a new realm for '$REALM'"
-sudo docker-compose exec keycloak \
+docker-compose exec keycloak \
   /opt/keycloak/bin/kcadm.sh \
   create realms \
   -s "realm=$REALM" \
@@ -30,7 +49,7 @@ sudo docker-compose exec keycloak \
 
 # https://github.com/hedgedoc/hedgedoc/issues/56
 info "Fix up a id bug"
-sudo docker-compose exec -T keycloak \
+docker-compose exec -T keycloak \
   /opt/keycloak/bin/kcadm.sh \
   create client-scopes \
   -r "$REALM" \
@@ -62,7 +81,7 @@ EOF
 
 
 info "Create an admin user in realm"
-sudo docker-compose exec -T keycloak \
+docker-compose exec -T keycloak \
   /opt/keycloak/bin/kcadm.sh \
   create users \
   -o \
diff --git a/mastodon/setup b/mastodon/setup
--- a/mastodon/setup
+++ b/mastodon/setup
@@ -10,27 +10,17 @@ source ./env.production
 mkdir -p data/system
 chmod 777 data/system
 
-rm -f env.secrets
-cat > env.secrets << EOF
-# Fake file to make db:setup happy
-SECRET_KEY_BASE=000000
-OTP_SECRET=000000
-OIDC_CLIENT_SECRET=000000
-EOF
+if [ -r "./env.secrets" ]; then
+	docker-compose up -d || die "unable to restart mastodon"
+	exit 0
+fi
 
 # have to bring it all down before we touch the files
 docker-compose down
 
-if [ -z "$MASTODON_SKIP_DB_INIT" ]; then
-	info "configuring mastodon"
-	sudo docker-compose run --rm mastodon \
-	  rails db:setup \
-	|| die "unable to login"
-fi
-
 OIDC_CLIENT_SECRET="$(openssl rand -hex 32)"
 
-# now create the real secrets file,
+# create the secrets file,
 # along with some parameters that should be in the environment
 cat <<EOF > env.secrets
 # DO NOT CHECK IN
@@ -43,12 +33,20 @@ SECRET_KEY_BASE=$(openssl rand -hex 32)
 OTP_SECRET=$(openssl rand -hex 32)
 EOF
 
+info "mastodon: creating push keys"
 docker-compose run --rm mastodon \
-  rails mastodon:webpush:generate_vapid_key \
-  >> env.secrets \
+	rails mastodon:webpush:generate_vapid_key \
+	>> env.secrets \
 || die "unable to generate vapid key"
 
+info "mastodon: setting up database"
+docker-compose run --rm mastodon \
+	rails db:setup \
+|| die "unable to login"
 
+source ./env.secrets
+
+info "mastodon: creating keycloak interface"
 ../keycloak/client-delete mastodon
 ../keycloak/client-create <<EOF || die "Unable to create keycloak client"
 {
@@ -62,4 +60,4 @@ docker-compose run --rm mastodon \
 }
 EOF
 
-docker-compose up -d
+docker-compose up -d || die "mastodon: unable to start container"
diff --git a/nextcloud/setup b/nextcloud/setup
--- a/nextcloud/setup
+++ b/nextcloud/setup
@@ -6,20 +6,23 @@ cd "$DIRNAME"
 source ../env.production || die "no top level env?"
 source env.production || die "no local env?"
 
-if [ ! -r "env.secrets" ]; then
-	NEXTCLOUD_CLIENT_SECRET="$(openssl rand -hex 32)"
-	NEXTCLOUD_ADMIN_PASSWORD="$(openssl rand -hex 4)"
+if [ -r "./env.secrets" ]; then
+	docker-compose up -d || die "nextcloud: unable to start"
+	exit 0
+fi
 
-	echo "Generating secrets: admin password $NEXTCLOUD_ADMIN_PASSWORD"
-	cat <<EOF > env.secrets
+docker-compose down 2>/dev/null
+
+NEXTCLOUD_CLIENT_SECRET="$(openssl rand -hex 32)"
+NEXTCLOUD_ADMIN_PASSWORD="$(openssl rand -hex 6)"
+
+echo "Generating secrets: admin password $NEXTCLOUD_ADMIN_PASSWORD"
+cat <<EOF > env.secrets
 # Do not check in!
 NEXTCLOUD_ADMIN_PASSWORD=$NEXTCLOUD_ADMIN_PASSWORD
 NEXTCLOUD_TRUSTED_DOMAINS=$NEXTCLOUD_HOSTNAME
 NEXTCLOUD_CLIENT_SECRET=$NEXTCLOUD_CLIENT_SECRET
 EOF
-else
-	source env.secrets || die "no secret env?"
-fi
 
 BASE="https://$KEYCLOAK_HOSTNAME/realms/$REALM/protocol/openid-connect"
 PROVIDER="$(jq -c . <<EOF
@@ -50,14 +53,13 @@ docker-compose up -d || die "unable to bring up docker"
 
 # wait for the nextcloud instance to be responsive
 # TODO: how to find out if it is ready?
-echo "SLEEPING..."
-sleep 30
-
+echo "Sleeping a minute while nextcloud installs"
+sleep 60
 
 
 docker-compose exec -u www-data -T nextcloud bash -x <<EOF || die "unable to configure sociallogin"
-./occ app:remove sociallogin || echo "not yet installed"
-./occ app:install sociallogin || exit 1
+./occ app:install calendar
+./occ app:install sociallogin
 ./occ config:app:set sociallogin prevent_create_email_exists --value=1 || exit 1
 ./occ config:app:set sociallogin update_profile_on_login --value=1 || exit 1
 ./occ config:app:set sociallogin custom_providers --value='$PROVIDER' || exit 1
